### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by GemOfLife** [chris13300/expToBook#1]
When trying to run the .exe from the releases Eman gets started sucessfully but then there is an exception (sorry it's in german)
Unbehandelte Ausnahme: System.ComponentModel.Win32Exception: Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start()
   bei expToBook.modFonctions.calculHash(String epd)
   bei expToBook.modMain.entreePolyglot(String positionEPD, String coup, Int32 pourcentage)
   bei expToBook.modMain.Main()

**Comment by GemOfLife** [comment]
First it wanted msvcr120d.dll. I downloaded it from the internet. Now the pg_key.exe seems to cause an exception.
Unbehandelte Ausnahme: System.ArgumentOutOfRangeException: Der Index und die Länge müssen sich auf eine Position in der Zeichenfolge beziehen.
Parametername: length
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei expToBook.modMain.entreePolyglot(String positionEPD, String coup, Int32 pourcentage)
   bei expToBook.modMain.Main()
Thanks for the help btw

**Comment by chris13300** [comment]
Try this command :
pg_key.exe "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

You should get this hash string :
463b96181691fc9c

**Comment by GemOfLife** [comment]
The issue is pg_key.exe doesn't start up at all. It can't be started correctly

**Comment by chris13300** [comment]
I found it [Here](http://hgm.nubati.net/book_format.html). It seems to work on all my systems (i5, i7, e3, e5, win7, win8.1). Sorry if it is incompatible with your hardware.

**Comment by GemOfLife** [comment]
Seems like it is incompatible with win10 then. No issue :)

**Comment by chris13300** [comment]
pg_key was coded (not by me) in C/C++ language years ago. Maybe on win10 you need to install [old DLLs](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) of Visual C++ redistribuable (vcredist).

**Comment by chris13300** [comment]
You need to copy [msvcp120d.dll](https://github.com/chris13300/expToBook/blob/main/expToBook/bin/Debug/msvcp120d.dll) and [msvcr120d.dll](https://github.com/chris13300/expToBook/blob/main/expToBook/bin/Debug/msvcr120d.dll) in your SysWOW64 folder.

**Comment by GemOfLife** [comment]
Thank you for your research/help. Now it works
